plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '8.8.0'
    id 'org.springdoc.openapi-gradle-plugin' version '1.9.0'
    id 'org.openapi.generator' version '7.16.0'
    id 'checkstyle'
}

checkstyle {
    toolVersion = '10.26.1'
    configFile = file("../config/checkstyle/checkstyle.xml")
}

tasks.named("checkstyleMain", Checkstyle) {
    include("**/*Controller.java")
    include("**/*Service.java")
    include("**/*Repository.java")
    include("**/*Mapper.java")
}

group = 'cloudflight.integra'
version = '0.0.1-SNAPSHOT'
description = 'backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    //bcrypt
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'org.mapstruct:mapstruct:1.6.3'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.4.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

test {
    useJUnitPlatform {
        if (project.hasProperty('excludeTags')) {
            excludeTags project.property('excludeTags').split(',')
        }
    }
}

spotless {
    java {
        palantirJavaFormat()
    }
}

openApi {
    apiDocsUrl.set("http://localhost:8080/v3/api-docs")
    outputDir.set(layout.buildDirectory.get().asFile)
    outputFileName.set("openapi.json")
    waitTimeInSeconds.set(10)
}

openApiGenerate {
    generatorName.set("typescript-axios")

    inputSpec.set(layout.buildDirectory.file("openapi.json").get().asFile.toURI().toString())

    outputDir.set(file("${projectDir}/../frontend/src/api/generated").absolutePath)

    configOptions.set([
        npmName: "api-client",
        supportsES6: "true"
    ])
}

tasks.named('openApiGenerate') {
    dependsOn 'generateOpenApiDocs'
}

tasks.register('generateApiClient') {
    group = "build"
    description = "Generates OpenAPI spec from controllers and outputs a TypeScript client."

    dependsOn 'openApiGenerate'
}



