### Get all users

GET {{host}}/api/users
Authorization: Bearer {{token}}

### Get user by id

GET {{host}}/api/users/1
Authorization: Bearer {{token}}

### Get user by id (failed - 404)

GET {{host}}/api/users/123
Authorization: Bearer {{token}}


### invite a user

POST {{host}}/api/users/invite
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "darius",
  "email": "dariusszocs11@gmail.com",
  "phone": "0747474747",
  "role": "PARTICIPANT"
}

### Create user

POST {{host}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "ionel",
  "email": "ionel@gmail.com",
  "password": "!IonelCelSmecher123",
  "phone": "0747474747",
  "role": "PARTICIPANT"
}

### Create user - same as above (failed)

POST {{host}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "ionel",
  "email": "ionel@gmail.com",
  "password": "!IonelCelSmecher123",
  "phone": "0747474747",
  "role": "PARTICIPANT"
}


### Create user - invalid fields

POST {{host}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "",
  "email": "ionel",
  "password": "123",
  "phone": "19fj352t",
  "role": "PARTICIPANT"
}

### Create user - invalid role field

POST {{host}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Johannis",
  "email": "johannis@gmail.com",
  "password": "!FicusMaximus123",
  "phone": "0723232323",
  "role": "PRESIDENT"
}

### Update user

PUT {{host}}/api/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "ionelionel",
  "email": "ionel@gmail.com",
  "password": "!IonelCelSmecher123",
  "phone": "+40712121212",
  "role": "PARTICIPANT"
}

### Delete user

DELETE {{host}}/api/users/22
Authorization: Bearer {{token}}

### Delete user (failed - 404)

DELETE {{host}}/api/users/123
Authorization: Bearer {{token}}